version: '3.8'

services:
  react-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: "task-manager-ui"
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider
    stdin_open: true
    tty: true
